### PR TITLE
implement color scheme

### LINKED ISSUE #40: Change app color scheme
also put more thought into semantics of each button and include in color scheme

### PR DESCRIPTION
**Pull request by oliviagiandrea**
fixes #40

### CODE REVIEW

**Review by wli-linda — COMMENTED** [review]
looks good!

**Comment by jrdegreeff** [comment]
looks solid so far! two quick thoughts before I go AFK:
- the green on red on the warning buttons doesn't look great
- would be nice to have something other than default link styling for the log table

**Comment by isabellapedraza** [comment]
It looks good to me except the grey on white is a bit strangle for me – how about switching the colors between the background of pages and the inside of the search box?

Screenshot 2022-12-12 at 5 37 13 PM

**Review by jrdegreeff — APPROVED** [review]
lgtm

**Pull request merged**
