### PR TITLE
frontend simplification

### PR DESCRIPTION
**Pull request by jrdegreeff**
final foray into my very late night mind from yesterday...

This stuff doesn't close any issues or anything but just general abstraction and consistency, etc.

### CODE REVIEW

**Review by wli-linda — DISMISSED** [review]

**Comment by jrdegreeff** [comment]
Ok I also just added a commit to center the header which I've been wanting to do for a while but might be a bit more controversial so requesting rereview from @wli-linda

**Review by wli-linda — COMMENTED** [review]
Ooh controversial indeed.... Aesthetically I'm fine with centering the header though you could argue it widens the distance between the left navbar and the top navbar links, making it harder for users to see/click (fitts law or something)

**Comment by jrdegreeff** [comment]
> Ooh controversial indeed.... Aesthetically I'm fine with centering the header though you could argue it widens the distance between the left navbar and the top navbar links, making it harder for users to see/click (fitts law or something)

That's a fair point. The original reason I wanted to do it a few days ago was that the home page currently looks really weird to me with centered body but left aligned header. And then for consistency I wanted to do that across the board.

**Comment by jrdegreeff** [comment]
@wli-linda how would you feel about merging this now and then letting Olivia have the final say as part of the polish PR she is working on?

**Review by wli-linda — APPROVED** [review]

**Pull request merged**
